// Code generated by MockGen. DO NOT EDIT.
// Source: /home/wil/sro/gameserver-service/pkg/repository/dimension.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=/home/wil/sro/gameserver-service/pkg/repository/dimension.go -destination=/home/wil/sro/gameserver-service/pkg/mocks/dimension_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	game "github.com/ShatteredRealms/gameserver-service/pkg/model/game"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDimensionRepository is a mock of DimensionRepository interface.
type MockDimensionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDimensionRepositoryMockRecorder
	isgomock struct{}
}

// MockDimensionRepositoryMockRecorder is the mock recorder for MockDimensionRepository.
type MockDimensionRepositoryMockRecorder struct {
	mock *MockDimensionRepository
}

// NewMockDimensionRepository creates a new mock instance.
func NewMockDimensionRepository(ctrl *gomock.Controller) *MockDimensionRepository {
	mock := &MockDimensionRepository{ctrl: ctrl}
	mock.recorder = &MockDimensionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDimensionRepository) EXPECT() *MockDimensionRepositoryMockRecorder {
	return m.recorder
}

// CreateDimension mocks base method.
func (m *MockDimensionRepository) CreateDimension(ctx context.Context, dimension *game.Dimension) (*game.Dimension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDimension", ctx, dimension)
	ret0, _ := ret[0].(*game.Dimension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDimension indicates an expected call of CreateDimension.
func (mr *MockDimensionRepositoryMockRecorder) CreateDimension(ctx, dimension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDimension", reflect.TypeOf((*MockDimensionRepository)(nil).CreateDimension), ctx, dimension)
}

// DeleteDimension mocks base method.
func (m *MockDimensionRepository) DeleteDimension(ctx context.Context, dimensionId *uuid.UUID) (*game.Dimension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDimension", ctx, dimensionId)
	ret0, _ := ret[0].(*game.Dimension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDimension indicates an expected call of DeleteDimension.
func (mr *MockDimensionRepositoryMockRecorder) DeleteDimension(ctx, dimensionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDimension", reflect.TypeOf((*MockDimensionRepository)(nil).DeleteDimension), ctx, dimensionId)
}

// GetDimensionById mocks base method.
func (m *MockDimensionRepository) GetDimensionById(ctx context.Context, dimensionId *uuid.UUID) (*game.Dimension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensionById", ctx, dimensionId)
	ret0, _ := ret[0].(*game.Dimension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDimensionById indicates an expected call of GetDimensionById.
func (mr *MockDimensionRepositoryMockRecorder) GetDimensionById(ctx, dimensionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensionById", reflect.TypeOf((*MockDimensionRepository)(nil).GetDimensionById), ctx, dimensionId)
}

// GetDimensions mocks base method.
func (m *MockDimensionRepository) GetDimensions(ctx context.Context) (*game.Dimensions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensions", ctx)
	ret0, _ := ret[0].(*game.Dimensions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDimensions indicates an expected call of GetDimensions.
func (mr *MockDimensionRepositoryMockRecorder) GetDimensions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensions", reflect.TypeOf((*MockDimensionRepository)(nil).GetDimensions), ctx)
}

// UpdateDimension mocks base method.
func (m *MockDimensionRepository) UpdateDimension(ctx context.Context, dimension *game.Dimension) (*game.Dimension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDimension", ctx, dimension)
	ret0, _ := ret[0].(*game.Dimension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDimension indicates an expected call of UpdateDimension.
func (mr *MockDimensionRepositoryMockRecorder) UpdateDimension(ctx, dimension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDimension", reflect.TypeOf((*MockDimensionRepository)(nil).UpdateDimension), ctx, dimension)
}
