// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.8
// source: sro/gameserver/connection.proto

package pb

import (
	context "context"
	pb "github.com/ShatteredRealms/go-common-service/pkg/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_ConnectGameServer_FullMethodName  = "/sro.gameserver.ConnectionService/ConnectGameServer"
	ConnectionService_VerifyConnect_FullMethodName      = "/sro.gameserver.ConnectionService/VerifyConnect"
	ConnectionService_TransferPlayer_FullMethodName     = "/sro.gameserver.ConnectionService/TransferPlayer"
	ConnectionService_IsCharacterPlaying_FullMethodName = "/sro.gameserver.ConnectionService/IsCharacterPlaying"
	ConnectionService_IsUserPlaying_FullMethodName      = "/sro.gameserver.ConnectionService/IsUserPlaying"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	ConnectGameServer(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectGameServerResponse, error)
	// Called by the gameserver to verifying and incoming connection
	// request. Returns the character id if the connection was successful
	VerifyConnect(ctx context.Context, in *VerifyConnectRequest, opts ...grpc.CallOption) (*pb.TargetId, error)
	TransferPlayer(ctx context.Context, in *TransferPlayerRequest, opts ...grpc.CallOption) (*ConnectGameServerResponse, error)
	IsCharacterPlaying(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectionStatus, error)
	IsUserPlaying(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectionStatus, error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) ConnectGameServer(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectGameServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectGameServerResponse)
	err := c.cc.Invoke(ctx, ConnectionService_ConnectGameServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) VerifyConnect(ctx context.Context, in *VerifyConnectRequest, opts ...grpc.CallOption) (*pb.TargetId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.TargetId)
	err := c.cc.Invoke(ctx, ConnectionService_VerifyConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) TransferPlayer(ctx context.Context, in *TransferPlayerRequest, opts ...grpc.CallOption) (*ConnectGameServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectGameServerResponse)
	err := c.cc.Invoke(ctx, ConnectionService_TransferPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) IsCharacterPlaying(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionStatus)
	err := c.cc.Invoke(ctx, ConnectionService_IsCharacterPlaying_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) IsUserPlaying(ctx context.Context, in *pb.TargetId, opts ...grpc.CallOption) (*ConnectionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionStatus)
	err := c.cc.Invoke(ctx, ConnectionService_IsUserPlaying_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
type ConnectionServiceServer interface {
	ConnectGameServer(context.Context, *pb.TargetId) (*ConnectGameServerResponse, error)
	// Called by the gameserver to verifying and incoming connection
	// request. Returns the character id if the connection was successful
	VerifyConnect(context.Context, *VerifyConnectRequest) (*pb.TargetId, error)
	TransferPlayer(context.Context, *TransferPlayerRequest) (*ConnectGameServerResponse, error)
	IsCharacterPlaying(context.Context, *pb.TargetId) (*ConnectionStatus, error)
	IsUserPlaying(context.Context, *pb.TargetId) (*ConnectionStatus, error)
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) ConnectGameServer(context.Context, *pb.TargetId) (*ConnectGameServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectGameServer not implemented")
}
func (UnimplementedConnectionServiceServer) VerifyConnect(context.Context, *VerifyConnectRequest) (*pb.TargetId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyConnect not implemented")
}
func (UnimplementedConnectionServiceServer) TransferPlayer(context.Context, *TransferPlayerRequest) (*ConnectGameServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferPlayer not implemented")
}
func (UnimplementedConnectionServiceServer) IsCharacterPlaying(context.Context, *pb.TargetId) (*ConnectionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsCharacterPlaying not implemented")
}
func (UnimplementedConnectionServiceServer) IsUserPlaying(context.Context, *pb.TargetId) (*ConnectionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserPlaying not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_ConnectGameServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.TargetId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).ConnectGameServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_ConnectGameServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).ConnectGameServer(ctx, req.(*pb.TargetId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_VerifyConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).VerifyConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_VerifyConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).VerifyConnect(ctx, req.(*VerifyConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_TransferPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).TransferPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_TransferPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).TransferPlayer(ctx, req.(*TransferPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_IsCharacterPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.TargetId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).IsCharacterPlaying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_IsCharacterPlaying_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).IsCharacterPlaying(ctx, req.(*pb.TargetId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_IsUserPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.TargetId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).IsUserPlaying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_IsUserPlaying_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).IsUserPlaying(ctx, req.(*pb.TargetId))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sro.gameserver.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectGameServer",
			Handler:    _ConnectionService_ConnectGameServer_Handler,
		},
		{
			MethodName: "VerifyConnect",
			Handler:    _ConnectionService_VerifyConnect_Handler,
		},
		{
			MethodName: "TransferPlayer",
			Handler:    _ConnectionService_TransferPlayer_Handler,
		},
		{
			MethodName: "IsCharacterPlaying",
			Handler:    _ConnectionService_IsCharacterPlaying_Handler,
		},
		{
			MethodName: "IsUserPlaying",
			Handler:    _ConnectionService_IsUserPlaying_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sro/gameserver/connection.proto",
}
