// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: sro/gameserver/connection.proto

package pb

import (
	pb "github.com/ShatteredRealms/go-common-service/pkg/pb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectGameServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectGameServerResponse) Reset() {
	*x = ConnectGameServerResponse{}
	mi := &file_sro_gameserver_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectGameServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectGameServerResponse) ProtoMessage() {}

func (x *ConnectGameServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sro_gameserver_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectGameServerResponse.ProtoReflect.Descriptor instead.
func (*ConnectGameServerResponse) Descriptor() ([]byte, []int) {
	return file_sro_gameserver_connection_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectGameServerResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConnectGameServerResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectGameServerResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type VerifyConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection id provided to the server by a pending connecting target
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Name of server verifying the connection request
	ServerName    string `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyConnectRequest) Reset() {
	*x = VerifyConnectRequest{}
	mi := &file_sro_gameserver_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectRequest) ProtoMessage() {}

func (x *VerifyConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sro_gameserver_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectRequest.ProtoReflect.Descriptor instead.
func (*VerifyConnectRequest) Descriptor() ([]byte, []int) {
	return file_sro_gameserver_connection_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyConnectRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VerifyConnectRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_sro_gameserver_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sro_gameserver_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_sro_gameserver_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type TransferPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Location      *pb.Location           `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPlayerRequest) Reset() {
	*x = TransferPlayerRequest{}
	mi := &file_sro_gameserver_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPlayerRequest) ProtoMessage() {}

func (x *TransferPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sro_gameserver_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPlayerRequest.ProtoReflect.Descriptor instead.
func (*TransferPlayerRequest) Descriptor() ([]byte, []int) {
	return file_sro_gameserver_connection_proto_rawDescGZIP(), []int{3}
}

func (x *TransferPlayerRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *TransferPlayerRequest) GetLocation() *pb.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_sro_gameserver_connection_proto protoreflect.FileDescriptor

const file_sro_gameserver_connection_proto_rawDesc = "" +
	"\n" +
	"\x1fsro/gameserver/connection.proto\x12\x0esro.gameserver\x1a\x1cgoogle/api/annotations.proto\x1a\x11sro/globals.proto\"n\n" +
	"\x19ConnectGameServerResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\"\\\n" +
	"\x14VerifyConnectRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\"*\n" +
	"\x10ConnectionStatus\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"`\n" +
	"\x15TransferPlayerRequest\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12)\n" +
	"\blocation\x18\x02 \x01(\v2\r.sro.LocationR\blocation2\xbb\x04\n" +
	"\x11ConnectionService\x12t\n" +
	"\x11ConnectGameServer\x12\r.sro.TargetId\x1a).sro.gameserver.ConnectGameServerResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/connect/character/id/{id}\x12c\n" +
	"\rVerifyConnect\x12$.sro.gameserver.VerifyConnectRequest\x1a\r.sro.TargetId\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/connect/verify\x12{\n" +
	"\x0eTransferPlayer\x12%.sro.gameserver.TransferPlayerRequest\x1a).sro.gameserver.ConnectGameServerResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/transfer\x12k\n" +
	"\x12IsCharacterPlaying\x12\r.sro.TargetId\x1a .sro.gameserver.ConnectionStatus\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/status/character/id/{id}\x12a\n" +
	"\rIsUserPlaying\x12\r.sro.TargetId\x1a .sro.gameserver.ConnectionStatus\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/status/user/id/{id}B9Z7github.com/ShatteredRealms/gameserver-service/pkg/pb;pbb\x06proto3"

var (
	file_sro_gameserver_connection_proto_rawDescOnce sync.Once
	file_sro_gameserver_connection_proto_rawDescData []byte
)

func file_sro_gameserver_connection_proto_rawDescGZIP() []byte {
	file_sro_gameserver_connection_proto_rawDescOnce.Do(func() {
		file_sro_gameserver_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sro_gameserver_connection_proto_rawDesc), len(file_sro_gameserver_connection_proto_rawDesc)))
	})
	return file_sro_gameserver_connection_proto_rawDescData
}

var file_sro_gameserver_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sro_gameserver_connection_proto_goTypes = []any{
	(*ConnectGameServerResponse)(nil), // 0: sro.gameserver.ConnectGameServerResponse
	(*VerifyConnectRequest)(nil),      // 1: sro.gameserver.VerifyConnectRequest
	(*ConnectionStatus)(nil),          // 2: sro.gameserver.ConnectionStatus
	(*TransferPlayerRequest)(nil),     // 3: sro.gameserver.TransferPlayerRequest
	(*pb.Location)(nil),               // 4: sro.Location
	(*pb.TargetId)(nil),               // 5: sro.TargetId
}
var file_sro_gameserver_connection_proto_depIdxs = []int32{
	4, // 0: sro.gameserver.TransferPlayerRequest.location:type_name -> sro.Location
	5, // 1: sro.gameserver.ConnectionService.ConnectGameServer:input_type -> sro.TargetId
	1, // 2: sro.gameserver.ConnectionService.VerifyConnect:input_type -> sro.gameserver.VerifyConnectRequest
	3, // 3: sro.gameserver.ConnectionService.TransferPlayer:input_type -> sro.gameserver.TransferPlayerRequest
	5, // 4: sro.gameserver.ConnectionService.IsCharacterPlaying:input_type -> sro.TargetId
	5, // 5: sro.gameserver.ConnectionService.IsUserPlaying:input_type -> sro.TargetId
	0, // 6: sro.gameserver.ConnectionService.ConnectGameServer:output_type -> sro.gameserver.ConnectGameServerResponse
	5, // 7: sro.gameserver.ConnectionService.VerifyConnect:output_type -> sro.TargetId
	0, // 8: sro.gameserver.ConnectionService.TransferPlayer:output_type -> sro.gameserver.ConnectGameServerResponse
	2, // 9: sro.gameserver.ConnectionService.IsCharacterPlaying:output_type -> sro.gameserver.ConnectionStatus
	2, // 10: sro.gameserver.ConnectionService.IsUserPlaying:output_type -> sro.gameserver.ConnectionStatus
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sro_gameserver_connection_proto_init() }
func file_sro_gameserver_connection_proto_init() {
	if File_sro_gameserver_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sro_gameserver_connection_proto_rawDesc), len(file_sro_gameserver_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sro_gameserver_connection_proto_goTypes,
		DependencyIndexes: file_sro_gameserver_connection_proto_depIdxs,
		MessageInfos:      file_sro_gameserver_connection_proto_msgTypes,
	}.Build()
	File_sro_gameserver_connection_proto = out.File
	file_sro_gameserver_connection_proto_goTypes = nil
	file_sro_gameserver_connection_proto_depIdxs = nil
}
