// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.8
// source: sro/gameserver/data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameServerDataService_GetGameServerDetails_FullMethodName = "/sro.gameserver.GameServerDataService/GetGameServerDetails"
)

// GameServerDataServiceClient is the client API for GameServerDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServerDataServiceClient interface {
	GetGameServerDetails(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GameServerDetails, error)
}

type gameServerDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServerDataServiceClient(cc grpc.ClientConnInterface) GameServerDataServiceClient {
	return &gameServerDataServiceClient{cc}
}

func (c *gameServerDataServiceClient) GetGameServerDetails(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GameServerDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameServerDetails)
	err := c.cc.Invoke(ctx, GameServerDataService_GetGameServerDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServerDataServiceServer is the server API for GameServerDataService service.
// All implementations must embed UnimplementedGameServerDataServiceServer
// for forward compatibility.
type GameServerDataServiceServer interface {
	GetGameServerDetails(context.Context, *emptypb.Empty) (*GameServerDetails, error)
	mustEmbedUnimplementedGameServerDataServiceServer()
}

// UnimplementedGameServerDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServerDataServiceServer struct{}

func (UnimplementedGameServerDataServiceServer) GetGameServerDetails(context.Context, *emptypb.Empty) (*GameServerDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameServerDetails not implemented")
}
func (UnimplementedGameServerDataServiceServer) mustEmbedUnimplementedGameServerDataServiceServer() {}
func (UnimplementedGameServerDataServiceServer) testEmbeddedByValue()                               {}

// UnsafeGameServerDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServerDataServiceServer will
// result in compilation errors.
type UnsafeGameServerDataServiceServer interface {
	mustEmbedUnimplementedGameServerDataServiceServer()
}

func RegisterGameServerDataServiceServer(s grpc.ServiceRegistrar, srv GameServerDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServerDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameServerDataService_ServiceDesc, srv)
}

func _GameServerDataService_GetGameServerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerDataServiceServer).GetGameServerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServerDataService_GetGameServerDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerDataServiceServer).GetGameServerDetails(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GameServerDataService_ServiceDesc is the grpc.ServiceDesc for GameServerDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServerDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sro.gameserver.GameServerDataService",
	HandlerType: (*GameServerDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameServerDetails",
			Handler:    _GameServerDataService_GetGameServerDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sro/gameserver/data.proto",
}
